services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: file
      POSTGRES_PASSWORD: file
      POSTGRES_DB: file
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: